CREATE TABLE IF NOT EXISTS users(
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NULL,
    trip_id UUID,
    FOREIGN KEY(trip_id) REFERENCES trips(id)
);